-- Registry for staging-only end-to-end verification runs (issue #174).
-- These tables may exist unused in production: production never enables the
-- internal E2E control routes or the E2E orphan janitor, so the tables stay
-- empty there. Nothing here is reachable by ordinary product APIs.
--
-- e2e_test_runs: one row per staging verification run. `id` is a
-- cryptographically random UUID generated by the caller (never derived from
-- email/branch/actor/token) and is the sole authority for resource ownership.
CREATE TABLE IF NOT EXISTS e2e_test_runs (
  id TEXT PRIMARY KEY,
  suite TEXT NOT NULL,
  source TEXT NOT NULL,
  github_run_id TEXT,
  github_run_attempt TEXT,
  commit_sha TEXT,
  status TEXT NOT NULL DEFAULT 'registered',
  cleanup_status TEXT NOT NULL DEFAULT 'not_started',
  failure_phase TEXT,
  failure_code TEXT,
  created_resource_count INTEGER NOT NULL DEFAULT 0,
  cleaned_resource_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  completed_at TEXT,
  cleanup_started_at TEXT,
  cleaned_at TEXT,
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS e2e_test_runs_expiry ON e2e_test_runs (status, expires_at);
CREATE INDEX IF NOT EXISTS e2e_test_runs_cleanup_status ON e2e_test_runs (cleanup_status);

-- e2e_test_resources: every resource created by a run, registered before or
-- immediately after creation. resource_type is a small code-defined
-- allowlist (see src/worker/e2e-registry.ts). NEVER store plaintext
-- tokens/hashes, cookies, OAuth tokens, webhook secrets, event payloads,
-- feedback/emails, Stripe keys, destination URLs, or R2 artifact contents
-- here — resource_ref is a non-sensitive identifier only (e.g. a job_key).
CREATE TABLE IF NOT EXISTS e2e_test_resources (
  run_id TEXT NOT NULL REFERENCES e2e_test_runs(id) ON DELETE CASCADE,
  resource_type TEXT NOT NULL,
  resource_ref TEXT NOT NULL,
  subtype TEXT,
  lifecycle TEXT NOT NULL DEFAULT 'planned',
  cleanup_attempts INTEGER NOT NULL DEFAULT 0,
  cleanup_failure_code TEXT,
  created_at TEXT,
  cleaned_at TEXT,
  PRIMARY KEY (run_id, resource_type, resource_ref)
);
CREATE INDEX IF NOT EXISTS e2e_test_resources_run ON e2e_test_resources (run_id);
CREATE INDEX IF NOT EXISTS e2e_test_resources_lifecycle ON e2e_test_resources (lifecycle);
